{% set name = "pycryptodomex" %}
{% set version = "3.6.3" %}
{% set sha256 = "008ad82b8fdd1532dd32a0e0e4204af8e4710fc3d2a76e408cbdb3dddf4f8417" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    # ctypes.util.find_library() isn't CONDA_PREFIX aware :'(
    # https://github.com/ContinuumIO/anaconda-issues/issues/1716
    - 0001-Make-load_lib-CONDA_PREFIX-aware.patch  # [unix]

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
    - toolchain
  run:
    - python
    - gmp   # [not win]
    - mpir  # [win]

test:
  imports:
    - Cryptodome
    - Cryptodome.Cipher
    - Cryptodome.Hash
    - Cryptodome.IO
    - Cryptodome.Math
    - Cryptodome.Protocol
    - Cryptodome.PublicKey
    - Cryptodome.Random
    - Cryptodome.SelfTest
    - Cryptodome.SelfTest.Cipher
    - Cryptodome.SelfTest.Hash
    - Cryptodome.SelfTest.IO
    - Cryptodome.SelfTest.Math
    - Cryptodome.SelfTest.Protocol
    - Cryptodome.SelfTest.PublicKey
    - Cryptodome.SelfTest.Random
    - Cryptodome.SelfTest.Signature
    - Cryptodome.SelfTest.Util
    - Cryptodome.Signature
    - Cryptodome.Util
  requires:
    - psutil

about:
  home: http://www.pycryptodome.org
  license: Public Domain/BSD 2-Clause/OCB/MPIR
  license_file: LICENSE.rst
  summary: Cryptographic library for Python
  description: |
    PyCryptodome is a self-contained Python package of low-level cryptographic
    primitives.
  doc_url: https://www.pycryptodome.org/en/latest/
  dev_url: https://github.com/Legrandin/pycryptodome

extra:
  recipe-maintainers:
    - nehaljwani
