appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: IOEhQvWaJhQBEzi0Eb42vA8brw851cwC2iO7cIFfRShSSMKeHYoKhPDbVGOwAtrRPp4csUtd22QXXHUtTxJm7AWunP5dSgTBXUfkVX/IY6HGhg09DZXWcbx/DcO8nrSxkbf7UZAGd69sLFHtwcyeCjgTBCdiwcccSDCPJSqTPPBF3jLjLV4+i76fQBboSsOSTZ/L15NgOJIukgPXN6V09IBko9mGDHjf9I9rM4tQ0IIeIJ88ATko//i7d/O8Ggd3EkdZsDPAwLbf5F12g3EtQzU9IwsB6UvzdYgzk9lWnDNtV9Ra/dC8TRvay43UpsE6qf3RzTuGuuW7XE4R3RglJpABOOWrLiSf50qwyVChJ3SWXX0DPUTwg/CAdNnToxFvksSrayYN5DWBrjBTchWhrauLYs8/CRe5wJblGsgQqwYLRXHL+W4frrbINGGtcxE8y2afPCiqwrX1qHg3W7L1aYYqSPYTfQ93GyXBdPfTJdw8EgkHkgncJAob6Ihbq92mLT4cBrBXEGdiBhe1BGzcULQr/lptjmSZBPXVthj+JrAxP4k27a0UKpBvMulu1hCYrz/fIY3GHiFddzw6+ISMohclDATVyDlcuLhdrjC9hP4XNBrvr3xa6OGS46thzsPWeDAIlYsnEFE47daaPJiPxUfQaIYmq+HmcgeYACmPHgo=}
